# Generated by Django 4.2.4 on 2023-09-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendos',
            name='idCliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='arriendos',
            name='idPelicula',
            field=models.IntegerField(null=True),
        ),
    ]
